apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  config : |
    server {
        listen 80 default_server;

        server_name test.lan;

        location = /health/ {
            add_header Content-Type text/plain;
            return 200 '{"status": "OK"}';
        }
    }