apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  config : |
    server {

        root /var/www/public_html;
        index index.php index.html;

        access_log /var/log/nginx/access-test.log;
        error_log /var/log/nginx/error-test.log;

        location / {
            try_files $uri /index.php$is_args$args;
        }

        location ~ \.php {
            try_files $uri =404;
            include fastcgi_params;
            fastcgi_pass php-service:9000;
            fastcgi_index index.php;
            fastcgi_send_timeout 21600;
            fastcgi_read_timeout 21600;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }