kind: ConfigMap
apiVersion: v1
metadata:
  name: php-config
data:
  DATABASE_DSN: 'mysql:dbname=homework;host=mysql'
  DATABASE_USERNAME: 'bx'
---
apiVersion: v1
kind: Secret
metadata:
  name: php-secret
type: Opaque
data:
  DATABASE_USERNAME: Yng=
  DATABASE_PASSWORD: MTEyMTEy