apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-monitor
  labels:
    app: app-monitor
spec:
  endpoints:
    - port: web
      scheme: http
      path: /metrics
      interval: 15s
  selector:
    matchLabels:
      app: app-monitor

---

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      prometheus: app-monitor