apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: app-monitor
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
  type: NodePort