GET http://test.lan/user/1

###

POST http://test.lan/user
Content-Type: application/x-www-form-urlencoded

username=MaLooo&firstName=Mary&lastName=Loo&email=ml@example.com&phone=+1 555 9995555

###

PUT http://test.lan/user/1?email=jddd@example.com&phone=+1 666 5555555

###

DELETE http://test.lan/user/1